/**
 * 新比赛批量入库（2026-09 批次4）—— 高校/中学生赛事 + 社会公开赛事
 * 数据来源：WebSearch 逐条核实的、仍在报名期的真实香港比赛（不编造、不含大陆征稿平台）
 * 关键字段（时间/地点/人群/人数/身份）全部预填确定值，不依赖 AI 抓取，确保真实性与确定性。
 * 运行: node scripts/scrape-batch4.mjs
 */
import { createClient } from '@supabase/supabase-js'
import { config } from 'dotenv'
import { resolve } from 'path'

config({ path: resolve(process.cwd(), '.env.local') })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
)

const normDate = (s) => (s ? String(s).slice(0, 10) : null)

// 字段说明（与 competitions 表约束严格对齐）：
// location: 港岛|九龙|新界|线上   eligibility: 个人报名|学校提名|两者皆可|不限
// team_size: 个人赛|2-3人|4-6人|7人以上|不限   age_group: 儿童|青少年|成人公开|不限
// status: 报名中|即将开始|已结束   date_start 为 NOT NULL，未知时用报名截止日兜底
const COMPETITIONS = [
  {
    url: 'https://www.scifac.hku.hk/events/sci-comm-contest-2026',
    title: '香港大學「科普傳意」比賽：破解迷思挑戰 2026',
    title_en: 'HKU Science Communication Contest — Myth Busters Challenge 2026',
    type: '其他',
    description: '香港大學理學院主辦的科學傳意比賽，以「破解迷思」為主題，學生組隊製作影片破解常見科學迷思。對象為香港、澳門及深圳 2026–27 學年就讀中三至中五的學生，3–6 人一隊，每間學校最多派出兩隊。首輪報名及提交截止 9 月 27 日。',
    date_start: '2026-09-27',
    date_end: '2026-12-13',
    deadline: '2026-09-27',
    location: '港岛',
    venue: '香港大學',
    fee_type: '有奖金',
    prize: '金獎 HK$12,000、銀獎 HK$6,000、銅獎 HK$4,500、最佳人氣獎 HK$1,500 等（每隊）',
    organizer: '香港大學理學院',
    registration_link: 'https://www.scifac.hku.hk/events/sci-comm-contest-2026',
    age_group: '青少年',
    team_size: '4-6人',
    eligibility: '学校提名',
    status: '报名中',
    source: '香港大學',
    universities: null,
  },
  {
    url: 'https://alipayhk.co/advicesecondary2026',
    title: 'AlipayHK αdvice 青年科創UX設計比賽暨工作影子計劃 2026',
    title_en: 'AlipayHK αdvice Youth FinTech UX Design Competition & Job Shadowing Programme 2026',
    type: 'AI创作',
    description: 'AlipayHK 主辦，SEED Foundation 及香港青年協會聯合主辦，教育局支持。中一至中六學生以個人或最多 4 人組隊，為 AlipayHK Super App 設計融入 AI 元素的新功能、主視覺與首頁 UI。截止報名 9 月 11 日，作品 11 月 13 日前提交，決賽及頒獎 12 月 12 日。',
    date_start: '2026-12-12',
    date_end: null,
    deadline: '2026-09-11',
    location: '线上',
    venue: null,
    fee_type: '免费',
    prize: '三甲可成為「初級首席創想官」，2027年7月參與工作影子計劃並赴螞蟻集團杭州總部交流',
    organizer: 'AlipayHK（SEED Foundation、香港青年協會聯合主辦）',
    registration_link: 'https://alipayhk.co/advicesecondary2026',
    age_group: '青少年',
    team_size: '不限',
    eligibility: '学校提名',
    status: '报名中',
    source: 'AlipayHK',
    universities: null,
  },
  {
    url: 'https://www.hkfew.org.hk/en/%e7%a4%be%e6%9c%83/%e5%90%88%e4%bd%9c/item/12714-%e3%80%90%e6%ad%a1%e8%bf%8e%e5%8f%83%e5%8a%a0%e3%80%91%e9%a6%99%e6%b8%af%e4%b8%ad%e5%ad%b8%e7%94%9f%e6%99%ae%e9%80%9a%e8%a9%b1%e6%bc%94%e8%ac%9b%e6%af%94%e8%b3%bd2026',
    title: '香港中學生普通話演講比賽 2026',
    title_en: 'Hong Kong Secondary School Putonghua Speech Competition 2026',
    type: '其他',
    description: '香港教育工作者聯會主辦的中學生普通話演講比賽，設初中組及高中組，須經就讀學校提名。截止報名 9 月 30 日，比賽暫定 12 月 19 日舉行。',
    date_start: '2026-12-19',
    date_end: null,
    deadline: '2026-09-30',
    location: '港岛',
    venue: null,
    fee_type: '免费',
    prize: null,
    organizer: '香港教育工作者聯會',
    registration_link: 'https://www.hkfew.org.hk/en/%e7%a4%be%e6%9c%83/%e5%90%88%e4%bd%9c/item/12714-%e3%80%90%e6%ad%a1%e8%bf%8e%e5%8f%83%e5%8a%a0%e3%80%91%e9%a6%99%e6%b8%af%e4%b8%ad%e5%ad%b8%e7%94%9f%e6%99%ae%e9%80%9a%e8%a9%b1%e6%bc%94%e8%ac%9b%e6%af%94%e8%b3%bd2026',
    age_group: '青少年',
    team_size: '个人赛',
    eligibility: '学校提名',
    status: '报名中',
    source: '香港教育工作者聯會',
    universities: null,
  },
  {
    url: 'https://ses.eduhk.hk/tc/node/5672',
    title: '「教育中學團體管理學校室內空氣質素」海報設計比賽',
    title_en: null,
    type: '创意摄影设计',
    description: '香港教育大學主辦的海報設計比賽，圍繞「學校室內空氣質素」主題，面向全港中學生。須由校方代表教師填寫報名，學生以個人或小組形式提交作品，截止 9 月 30 日，結果 11 月公佈。',
    date_start: '2026-09-30',
    date_end: null,
    deadline: '2026-09-30',
    location: '新界',
    venue: null,
    fee_type: '免费',
    prize: null,
    organizer: '香港教育大學',
    registration_link: 'https://ses.eduhk.hk/tc/node/5672',
    age_group: '青少年',
    team_size: '不限',
    eligibility: '学校提名',
    status: '报名中',
    source: '香港教育大學',
    universities: null,
  },
  {
    url: 'https://hkliterature.com/index/news/detail.html?id=12',
    title: '香港校園文學創作大賽 2026',
    title_en: null,
    type: '其他',
    description: '香港文學出版社、招商局集團香港青年聯合會主辦，面向香港學生，設大專組、高中組、初中組、小學高年級組。分徵文及現場創作兩環節，先提交徵文作品，入圍者再參加現場創作。徵稿期 4 月 1 日至 9 月 30 日。',
    date_start: '2026-09-30',
    date_end: null,
    deadline: '2026-09-30',
    location: '线上',
    venue: null,
    fee_type: '免费',
    prize: null,
    organizer: '香港文學出版社、招商局集團香港青年聯合會',
    registration_link: 'https://hkliterature.com/index/news/detail.html?id=12',
    age_group: '不限',
    team_size: '个人赛',
    eligibility: '个人报名',
    status: '报名中',
    source: '香港文學出版社',
    universities: null,
  },
  {
    url: 'https://www.wenweipo.com/a/202609/01/AP6a96ac87e4b0c1e500271d87.html',
    title: '香港中華遊樂會全港網球公開賽 2026（CRC Open）',
    title_en: 'CRC Open 2026 — Hong Kong Tennis Open',
    type: '运动',
    description: '香港中華遊樂會主辦的全港網球公開賽，10 月 24 日開鑼、賽期約六星期。設公開組、18 歲或以下及 14 歲或以下青少年組，另新增 5 個元老組別，獎金獎品總值逾 40 萬港元。9 月 1 日起接受公眾報名，9 月 27 日截止。',
    date_start: '2026-10-24',
    date_end: null,
    deadline: '2026-09-27',
    location: '港岛',
    venue: '香港中華遊樂會',
    fee_type: '付费',
    prize: '獎金獎品總值逾 40 萬港元',
    organizer: '香港中華遊樂會',
    registration_link: 'https://www.wenweipo.com/a/202609/01/AP6a96ac87e4b0c1e500271d87.html',
    age_group: '成人公开',
    team_size: '个人赛',
    eligibility: '个人报名',
    status: '报名中',
    source: '香港中華遊樂會',
    universities: null,
  },
  {
    url: 'https://www.art-mate.net/en/doc/98450',
    title: 'Star Dream Cup 2026：香港舞蹈公開賽',
    title_en: 'Star Dream Cup 2026: Hong Kong Dance Open',
    type: '其他',
    description: '香港舞蹈公開賽，項目涵蓋藝術體操舞蹈、芭蕾舞、爵士舞、現代舞、K-POP、中國舞、東方舞等。10 月 11 日於觀塘基督教家庭服務中心禮堂舉行，8 月 18 日至 9 月 23 日接受報名（早鳥優惠至 9 月 12 日）。',
    date_start: '2026-10-11',
    date_end: null,
    deadline: '2026-09-23',
    location: '九龙',
    venue: '觀塘基督教家庭服務中心禮堂',
    fee_type: '付费',
    prize: null,
    organizer: 'Star Dream',
    registration_link: 'https://www.art-mate.net/en/doc/98450',
    age_group: '不限',
    team_size: '不限',
    eligibility: '个人报名',
    status: '报名中',
    source: 'Star Dream',
    universities: null,
  },
  {
    url: 'https://smoothcomp.com/jp/event/33235',
    title: 'COPA DE HK — 香港國際格鬥（纏鬥）錦標賽 2026',
    title_en: 'COPA DE HK — Hong Kong International Grappling Tournament 2026',
    type: '运动',
    description: '香港國際格鬥（巴西柔術/纏鬥）錦標賽，10 月 17 至 18 日於伊利沙伯體育館舉行。設 Adult（18+）、Master 1（30+）、Master 2（36+）、Master 3（41+）等組別，10 月 4 日截止報名。',
    date_start: '2026-10-17',
    date_end: '2026-10-18',
    deadline: '2026-10-04',
    location: '港岛',
    venue: '伊利沙伯體育館',
    fee_type: '付费',
    prize: null,
    organizer: 'COPA de HK',
    registration_link: 'https://smoothcomp.com/jp/event/33235',
    age_group: '成人公开',
    team_size: '个人赛',
    eligibility: '个人报名',
    status: '报名中',
    source: 'COPA de HK',
    universities: null,
  },
  {
    url: 'https://www.cycling.org.hk/event/2026-2027-%e5%85%a8%e6%b8%af%e5%85%ac%e8%b7%af%e5%96%ae%e8%bb%8a%e8%b3%bd-%e7%ac%ac%e4%b8%89%e5%9b%9e%e5%90%88-%e5%a4%a7%e5%9f%94%e6%96%b0%e5%a8%98%e6%bd%ad%e8%b7%af-hong-kong-road-cycling-race/',
    title: '2026-2027 全港公路單車賽（第三回合·大埔新娘潭路）',
    title_en: 'Hong Kong Road Cycling Race — Series 3 (Brides Pool Road, Taipo)',
    type: '运动',
    description: '中國香港單車總會主辦的全港公路單車賽第三回合，於大埔新娘潭路舉行，名額 120 人。參賽者須為中國香港單車總會 2026–27 已繳保險費之會員，屬會優先報名至 9 月 25 日，公開網上報名 9 月 28 日起至 10 月 23 日（額滿即止）。',
    date_start: '2026-10-23',
    date_end: null,
    deadline: '2026-10-23',
    location: '新界',
    venue: '大埔新娘潭路',
    fee_type: '付费',
    prize: null,
    organizer: '中國香港單車總會',
    registration_link: 'https://www.cycling.org.hk/event/2026-2027-%e5%85%a8%e6%b8%af%e5%85%ac%e8%b7%af%e5%96%ae%e8%bb%8a%e8%b3%bd-%e7%ac%ac%e4%b8%89%e5%9b%9e%e5%90%88-%e5%a4%a7%e5%9f%94%e6%96%b0%e5%a8%98%e6%bd%ad%e8%b7%af-hong-kong-road-cycling-race/',
    age_group: '成人公开',
    team_size: '个人赛',
    eligibility: '个人报名',
    status: '报名中',
    source: '中國香港單車總會',
    universities: null,
  },
  {
    url: 'https://hk.sports.yahoo.com/news/%E8%B3%BD%E4%BA%8B-%E5%85%A8%E6%B8%AF%E6%9C%80%E5%B9%B3%E5%9D%A6%E7%A0%B4-pb-%E9%BB%83%E9%87%91%E8%B3%BD%E9%81%93%E4%B9%8B-%E8%B7%91%E6%89%8B%E5%A0%82%E9%95%B7%E8%B7%91%E9%8C%A6%E6%A8%99%E8%B3%BD-090000232.html',
    title: '跑手堂長跑錦標賽 2026',
    title_en: 'Runner Hall Long Run Championship 2026',
    type: '运动',
    description: '跑手堂主辦的長跑錦標賽，於全港最平坦的「破 PB 黃金賽道」舉行，10 月 25 日開跑。即日起公開報名，先到先得、額滿即止。',
    date_start: '2026-10-25',
    date_end: null,
    deadline: null,
    location: '新界',
    venue: null,
    fee_type: '付费',
    prize: null,
    organizer: '跑手堂',
    registration_link: 'https://hk.sports.yahoo.com/news/%E8%B3%BD%E4%BA%8B-%E5%85%A8%E6%B8%AF%E6%9C%80%E5%B9%B3%E5%9D%A6%E7%A0%B4-pb-%E9%BB%83%E9%87%91%E8%B3%BD%E9%81%93%E4%B9%8B-%E8%B7%91%E6%89%8B%E5%A0%82%E9%95%B7%E8%B7%91%E9%8C%A6%E6%A8%99%E8%B3%BD-090000232.html',
    age_group: '成人公开',
    team_size: '个人赛',
    eligibility: '个人报名',
    status: '报名中',
    source: '跑手堂',
    universities: null,
  },
  {
    url: 'https://raceresults.com.hk/event/464',
    title: '2026 TTR Charity Run 越野童樂慈善賽',
    title_en: '2026 TTR Charity Run',
    type: '运动',
    description: '越野童樂慈善賽，設 5 公里、2.5 公里、1.5 公里、10 公里及 25 公里賽程，10 月 17 至 18 日舉行，10 月 8 日截止報名。',
    date_start: '2026-10-17',
    date_end: '2026-10-18',
    deadline: '2026-10-08',
    location: '新界',
    venue: null,
    fee_type: '付费',
    prize: null,
    organizer: '越野童樂（TTR）',
    registration_link: 'https://raceresults.com.hk/event/464',
    age_group: '不限',
    team_size: '个人赛',
    eligibility: '个人报名',
    status: '报名中',
    source: '越野童樂',
    universities: null,
  },
  {
    url: 'https://www.search.gov.hk/viewer.html?url=https%3A%2F%2Fwww.investhk.gov.hk%2Fzh-hk%2Fnews%2Fglobal-fast-track-2026-opens-for-applications-expanded-eight-vertical-line-up-and-new-online-market-readiness-programme-to-support-global-startup-expansion-into-asia-via-hong-kong%2F',
    title: '全球 Fast Track 計劃 2026',
    title_en: 'Global Fast Track Programme 2026',
    type: '创业路演',
    description: '香港投資推廣署（InvestHK）主辦的全球初創競賽計劃，首設八大領域及線上市場先導計劃，助環球初創以香港為跳板進軍亞洲。5 月 4 日起接受報名，9 月 25 日截止。',
    date_start: '2026-09-25',
    date_end: null,
    deadline: '2026-09-25',
    location: '线上',
    venue: null,
    fee_type: '免费',
    prize: null,
    organizer: '香港投資推廣署（InvestHK）',
    registration_link: 'https://www.investhk.gov.hk/zh-hk/news/global-fast-track-2026-opens-for-applications-expanded-eight-vertical-line-up-and-new-online-market-readiness-programme-to-support-global-startup-expansion-into-asia-via-hong-kong/',
    age_group: '成人公开',
    team_size: '不限',
    eligibility: '个人报名',
    status: '报名中',
    source: '香港投資推廣署',
    universities: null,
  },
]

async function main() {
  console.log(`🔍 待入库 ${COMPETITIONS.length} 条已核实比赛\n`)
  let added = 0, skipped = 0, failed = 0

  for (const c of COMPETITIONS) {
    const { data: existing } = await supabase
      .from('competitions')
      .select('id')
      .eq('source_url', c.url)
      .maybeSingle()
    if (existing) { console.log(`⏭ 已存在: ${c.title.slice(0, 40)}`); skipped++; continue }

    const dateStart = normDate(c.date_start) || normDate(c.deadline)

    const { error } = await supabase.from('competitions').insert({
      title: c.title.slice(0, 200),
      title_en: c.title_en?.slice(0, 200) || null,
      type: c.type,
      description: c.description?.slice(0, 1000) || null,
      date_start: dateStart,
      date_end: normDate(c.date_end),
      registration_deadline: normDate(c.deadline),
      location: c.location,
      venue: c.venue?.slice(0, 200) || null,
      fee_type: c.fee_type || '付费',
      fee_amount: null,
      prize: c.prize?.slice(0, 200) || null,
      organizer: c.organizer?.slice(0, 200) || null,
      registration_link: (c.registration_link || c.url).slice(0, 500),
      age_group: c.age_group || '不限',
      team_size: c.team_size || '不限',
      eligibility: c.eligibility || '不限',
      status: c.status || '报名中',
      source: c.source,
      source_url: c.url,
      target_universities: c.universities,
      review_status: 'pending',
    })

    if (error) { console.log(`  ❌ ${c.title.slice(0, 40)}: ${error.message}`); failed++ }
    else { console.log(`  ✅ [${c.type}] ${c.title.slice(0, 50)}`); added++ }

    await new Promise(r => setTimeout(r, 200))
  }

  console.log(`\n✅ 新增 ${added} | ⏭ 跳过 ${skipped} | ❌ 失败 ${failed}`)
  const { count } = await supabase.from('competitions').select('id', { count: 'exact', head: true })
  console.log(`📦 数据库总计: ${count}`)
}

main().catch(console.error)
